### DISCUSSION TITLE
Trying to get HA Glances data to show up in a homepage running on different server

### DISCUSSION THREAD

**Discussion by kmanan** [hassio-addons/app-glances#465] [Q&A]
Hi. I'm trying to get the HA glances data to show up in gethomepage.dev homepage that I have on a different server. I've tried a lot of permutations and combinations from the glances services catalog but am unable to get this to work. Do you have ideas on what I can try to get the data?

**Comment by FriedCheese2006** [comment]
A year later. 

1. Install the add-on as normal.
2. Under the add-on configuration enable "Show disabled ports" and set the port you want the Glances web ui on. ![image](https://github.com/user-attachments/assets/86b2fc30-48aa-402f-8d8b-188bc62451af)
3. Setup a local user in HA for authenticating to the web ui.
4. Configure glances remote. Here's an example widget for homepage:

```
- glances:
    url: http://ha-url/ip:64646/
    username: glances
    password: glances
    cpu: true
    mem: true
    disk: / 
    diskUnits: bytes 
    expanded: true 
    label: HA 
```

I'm only getting CPU and memory usage by default though.
